#include <stdio.h>

struct Employee {
    int id;
        char name[50];
            float basicSalary;
                float hra;
                    float da;
                        float netSalary;
                        };

                        int main() {
                            struct Employee emp[100];
                                int n = 0, choice, searchId, i;

                                    while (1) {
                                            printf("\n===== Salary Management System =====\n");
                                                    printf("1. Add Employee Salary Details\n");
                                                            printf("2. Display Employee Records\n");
                                                                    printf("3. Search Employee\n");
                                                                            printf("4. Exit\n");
                                                                                    printf("Enter your choice: ");
                                                                                            scanf("%d", &choice);

                                                                                                    switch (choice) {
                                                                                                                case 1:
                                                                                                                                printf("Enter Employee ID: ");
                                                                                                                                                scanf("%d", &emp[n].id);

                                                                                                                                                                printf("Enter Employee Name: ");
                                                                                                                                                                                scanf("%s", emp[n].name);

                                                                                                                                                                                                printf("Enter Basic Salary: ");
                                                                                                                                                                                                                scanf("%f", &emp[n].basicSalary);

                                                                                                                                                                                                                                emp[n].hra = 0.20 * emp[n].basicSalary; // 20% HRA
                                                                                                                                                                                                                                                emp[n].da = 0.10 * emp[n].basicSalary;  // 10% DA
                                                                                                                                                                                                                                                                emp[n].netSalary =
                                                                                                                                                                                                                                                                                    emp[n].basicSalary + emp[n].hra + emp[n].da;

                                                                                                                                                                                                                                                                                                    n++;
                                                                                                                                                                                                                                                                                                                    printf("Employee salary record added successfully!\n");
                                                                                                                                                                                                                                                                                                                                    break;

                                                                                                                                                                                                                                                                                                                                                case 2:
                                                                                                                                                                                                                                                                                                                                                                if (n == 0) {
                                                                                                                                                                                                                                                                                                                                                                                    printf("No records found!\n");
                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                        printf("\n--- Employee Salary Records ---\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                            for (i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("ID: %d\n", emp[i].id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Name: %s\n", emp[i].name);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Basic Salary: %.2f\n", emp[i].basicSalary);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("HRA: %.2f\n", emp[i].hra);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("DA: %.2f\n", emp[i].da);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Net Salary: %.2f\n\n", emp[i].netSalary);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case 3:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Enter Employee ID to search: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            scanf("%d", &searchId);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (emp[i].id == searchId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("\nEmployee Found!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("ID: %d\n", emp[i].id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Name: %s\n", emp[i].name);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Net Salary: %.2f\n", emp[i].netSalary);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (i == n)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Employee not found!\n");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case 4:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Exiting program...\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Invalid choice!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }