#include <stdio.h>

struct Student {
    int rollNo;
        char name[50];
            float marks;
            };

            int main() {
                struct Student students[100];
                    int n = 0, choice, searchRoll, i;

                        while (1) {
                                printf("\n===== Student Record Management System =====\n");
                                        printf("1. Add Student\n");
                                                printf("2. Display Students\n");
                                                        printf("3. Search Student\n");
                                                                printf("4. Exit\n");
                                                                        printf("Enter your choice: ");
                                                                                scanf("%d", &choice);

                                                                                        switch (choice) {
                                                                                                    case 1:
                                                                                                                    printf("Enter Roll Number: ");
                                                                                                                                    scanf("%d", &students[n].rollNo);

                                                                                                                                                    printf("Enter Name: ");
                                                                                                                                                                    scanf("%s", students[n].name);

                                                                                                                                                                                    printf("Enter Marks: ");
                                                                                                                                                                                                    scanf("%f", &students[n].marks);

                                                                                                                                                                                                                    n++;
                                                                                                                                                                                                                                    printf("Student record added successfully!\n");
                                                                                                                                                                                                                                                    break;

                                                                                                                                                                                                                                                                case 2:
                                                                                                                                                                                                                                                                                if (n == 0) {
                                                                                                                                                                                                                                                                                                    printf("No records found!\n");
                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                        printf("\n--- Student Records ---\n");
                                                                                                                                                                                                                                                                                                                                                            for (i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                    printf("Roll No: %d\n", students[i].rollNo);
                                                                                                                                                                                                                                                                                                                                                                                                            printf("Name: %s\n", students[i].name);
                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Marks: %.2f\n\n", students[i].marks);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    case 3:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Enter Roll Number to search: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    scanf("%d", &searchRoll);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (students[i].rollNo == searchRoll) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("\nStudent Found!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Roll No: %d\n", students[i].rollNo);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Name: %s\n", students[i].name);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Marks: %.2f\n", students[i].marks);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (i == n) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Student not found!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    case 4:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Exiting program...\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Invalid choice!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }