#include <stdio.h>

struct Employee {
    int id;
        char name[50];
            float salary;
            };

            int main() {
                struct Employee emp[100];
                    int n = 0, choice, searchId, i;

                        while (1) {
                                printf("\n===== Employee Management System =====\n");
                                        printf("1. Add Employee\n");
                                                printf("2. Display Employees\n");
                                                        printf("3. Search Employee\n");
                                                                printf("4. Exit\n");
                                                                        printf("Enter your choice: ");
                                                                                scanf("%d", &choice);

                                                                                        switch (choice) {
                                                                                                    case 1:
                                                                                                                    printf("Enter Employee ID: ");
                                                                                                                                    scanf("%d", &emp[n].id);

                                                                                                                                                    printf("Enter Employee Name: ");
                                                                                                                                                                    scanf("%s", emp[n].name);

                                                                                                                                                                                    printf("Enter Employee Salary: ");
                                                                                                                                                                                                    scanf("%f", &emp[n].salary);

                                                                                                                                                                                                                    n++;
                                                                                                                                                                                                                                    printf("Employee added successfully!\n");
                                                                                                                                                                                                                                                    break;

                                                                                                                                                                                                                                                                case 2:
                                                                                                                                                                                                                                                                                if (n == 0) {
                                                                                                                                                                                                                                                                                                    printf("No employee records found!\n");
                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                        printf("\n--- Employee Records ---\n");
                                                                                                                                                                                                                                                                                                                                                            for (i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                    printf("ID: %d\n", emp[i].id);
                                                                                                                                                                                                                                                                                                                                                                                                            printf("Name: %s\n", emp[i].name);
                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Salary: %.2f\n\n", emp[i].salary);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    case 3:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Enter Employee ID to search: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    scanf("%d", &searchId);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (emp[i].id == searchId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("\nEmployee Found!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("ID: %d\n", emp[i].id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Name: %s\n", emp[i].name);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Salary: %.2f\n", emp[i].salary);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (i == n) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Employee not found!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    case 4:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Exiting program...\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Invalid choice!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }