import java.util.*;

class Book {
    int id;
        String title;
            String author;
                boolean isIssued;

                    Book(int id, String title, String author) {
                            this.id       = id;
                                    this.title    = title;
                                            this.author   = author;
                                                    this.isIssued = false;
                                                        }

                                                            void display() {
                                                                    System.out.printf("%-5d %-20s %-15s %-10s%n",
                                                                                id, title, author, isIssued ? "Issued" : "Available");
                                                                                    }
                                                                                    }

                                                                                    public class LibraryManagementSystem {

                                                                                        static ArrayList<Book> books = new ArrayList<>();
                                                                                            static Scanner sc = new Scanner(System.in);
                                                                                                static int nextId = 1;

                                                                                                    public static void main(String[] args) {
                                                                                                            int choice;
                                                                                                                    do {
                                                                                                                                printMenu();
                                                                                                                                            choice = sc.nextInt();

                                                                                                                                                        switch (choice) {
                                                                                                                                                                        case 1: addBook();        break;
                                                                                                                                                                                        case 2: displayBooks();   break;
                                                                                                                                                                                                        case 3: issueBook();      break;
                                                                                                                                                                                                                        case 4: returnBook();     break;
                                                                                                                                                                                                                                        case 5: searchBook();     break;
                                                                                                                                                                                                                                                        case 6: deleteBook();     break;
                                                                                                                                                                                                                                                                        case 7: System.out.println("Exiting... Goodbye!"); break;
                                                                                                                                                                                                                                                                                        default: System.out.println("Invalid choice! Try again.");
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                            } while (choice != 7);
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                    static void printMenu() {
                                                                                                                                                                                                                                                                                                                            System.out.println("\n===== LIBRARY MANAGEMENT SYSTEM =====");
                                                                                                                                                                                                                                                                                                                                    System.out.println("1. Add Book");
                                                                                                                                                                                                                                                                                                                                            System.out.println("2. Display All Books");
                                                                                                                                                                                                                                                                                                                                                    System.out.println("3. Issue Book");
                                                                                                                                                                                                                                                                                                                                                            System.out.println("4. Return Book");
                                                                                                                                                                                                                                                                                                                                                                    System.out.println("5. Search Book");
                                                                                                                                                                                                                                                                                                                                                                            System.out.println("6. Delete Book");
                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("7. Exit");
                                                                                                                                                                                                                                                                                                                                                                                            System.out.print("Enter your choice: ");
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                    static void addBook() {
                                                                                                                                                                                                                                                                                                                                                                                                            sc.nextLine();   // clear buffer
                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.print("Enter book title : ");
                                                                                                                                                                                                                                                                                                                                                                                                                            String title = sc.nextLine();
                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.print("Enter author name: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                            String author = sc.nextLine();

                                                                                                                                                                                                                                                                                                                                                                                                                                                    Book book = new Book(nextId++, title, author);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            books.add(book);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("Book added successfully! ID = " + book.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            static void displayBooks() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (books.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println("No books in the library.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("\n" + "-".repeat(55));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.printf("%-5s %-20s %-15s %-10s%n",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "ID", "Title", "Author", "Status");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("-".repeat(55));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (Book b : books) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            b.display();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("-".repeat(55));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    static void issueBook() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.print("Enter Book ID to issue: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int id = sc.nextInt();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Book book = findBookById(id);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (book == null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println("Book not found!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else if (book.isIssued) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("Book is already issued!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        book.isIssued = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("Book \"" + book.title + "\" issued successfully!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    static void returnBook() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.print("Enter Book ID to return: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int id = sc.nextInt();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Book book = findBookById(id);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (book == null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println("Book not found!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else if (!book.isIssued) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("Book was not issued!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        book.isIssued = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("Book \"" + book.title + "\" returned successfully!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    static void searchBook() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sc.nextLine();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.print("Enter title/author keyword to search: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            String keyword = sc.nextLine().toLowerCase();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    boolean found = false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (Book b : books) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (b.title.toLowerCase().contains(keyword) ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        b.author.toLowerCase().contains(keyword)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        b.display();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        found = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!found) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println("No matching books found.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                static void deleteBook() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.print("Enter Book ID to delete: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int id = sc.nextInt();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Book book = findBookById(id);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (book == null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("Book not found!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                books.remove(book);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("Book \"" + book.title + "\" deleted successfully!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            static Book findBookById(int id) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (Book b : books) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (b.id == id) return b;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }