class Ticket:
        def __init__(self, ticket_id, passenger_name, seat_no, destination, fare):
                self.ticket_id       = ticket_id
                        self.passenger_name  = passenger_name
                                self.seat_no         = seat_no
                                        self.destination     = destination
                                                self.fare            = fare
                                                        self.is_cancelled    = False

                                                            def display(self):
                                                                    status = "Cancelled ❌" if self.is_cancelled else "Confirmed ✅"
                                                                            print(f"{self.ticket_id:<8}{self.passenger_name:<15}"
                                                                                          f"{self.seat_no:<8}{self.destination:<15}"
                                                                                                        f"{self.fare:<10.2f}{status}")


                                                                                                        class TicketBookingSystem:
                                                                                                            def __init__(self, total_seats=20):
                                                                                                                    self.tickets       = {}
                                                                                                                            self.next_ticket_id = 1
                                                                                                                                    self.total_seats    = total_seats
                                                                                                                                            self.booked_seats   = set()

                                                                                                                                                def book_ticket(self):
                                                                                                                                                        if len(self.booked_seats) >= self.total_seats:
                                                                                                                                                                    print("Sorry, all seats are fully booked! ❌")
                                                                                                                                                                                return

                                                                                                                                                                                        name        = input("Enter passenger name : ")
                                                                                                                                                                                                destination = input("Enter destination     : ")
                                                                                                                                                                                                        fare         = float(input("Enter fare amount    : "))

                                                                                                                                                                                                                seat_no = self.allocate_seat()
                                                                                                                                                                                                                        ticket  = Ticket(self.next_ticket_id, name, seat_no, destination, fare)
                                                                                                                                                                                                                                self.tickets[self.next_ticket_id] = ticket
                                                                                                                                                                                                                                        self.booked_seats.add(seat_no)

                                                                                                                                                                                                                                                print(f"\n✅ Ticket booked successfully!")
                                                                                                                                                                                                                                                        print(f"   Ticket ID  : {ticket.ticket_id}")
                                                                                                                                                                                                                                                                print(f"   Seat No    : {seat_no}")
                                                                                                                                                                                                                                                                        print(f"   Fare       : {fare}")

                                                                                                                                                                                                                                                                                self.next_ticket_id += 1

                                                                                                                                                                                                                                                                                    def allocate_seat(self):
                                                                                                                                                                                                                                                                                            for seat in range(1, self.total_seats + 1):
                                                                                                                                                                                                                                                                                                        if seat not in self.booked_seats:
                                                                                                                                                                                                                                                                                                                        return seat
                                                                                                                                                                                                                                                                                                                                return None

                                                                                                                                                                                                                                                                                                                                    def cancel_ticket(self):
                                                                                                                                                                                                                                                                                                                                            ticket_id = int(input("Enter Ticket ID to cancel: "))
                                                                                                                                                                                                                                                                                                                                                    ticket    = self.tickets.get(ticket_id)

                                                                                                                                                                                                                                                                                                                                                            if not ticket:
                                                                                                                                                                                                                                                                                                                                                                        print("Ticket not found! ❌")
                                                                                                                                                                                                                                                                                                                                                                                elif ticket.is_cancelled:
                                                                                                                                                                                                                                                                                                                                                                                            print("Ticket is already cancelled! ❌")
                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                ticket.is_cancelled = True
                                                                                                                                                                                                                                                                                                                                                                                                                            self.booked_seats.discard(ticket.seat_no)
                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Ticket {ticket_id} cancelled successfully! "
                                                                                                                                                                                                                                                                                                                                                                                                                                                          f"Refund amount: {ticket.fare}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                              def search_ticket(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ticket_id = int(input("Enter Ticket ID to search: "))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ticket    = self.tickets.get(ticket_id)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if ticket:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  print("\nTicket Details:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              self.print_header()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ticket.display()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              print("Ticket not found! ❌")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  def display_all_tickets(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if not self.tickets:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      print("No tickets booked yet.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          print("\nAll Booked Tickets:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  self.print_header()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          for ticket in self.tickets.values():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ticket.display()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          def print_header(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  print("-" * 65)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          print(f"{'ID':<8}{'Name':<15}{'Seat':<8}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"{'Destination':<15}{'Fare':<10}Status")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("-" * 65)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def show_availability(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            available = self.total_seats - len(self.booked_seats)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"\nTotal Seats     : {self.total_seats}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Booked Seats    : {len(self.booked_seats)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"Available Seats : {available}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def calculate_revenue(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                total = sum(t.fare for t in self.tickets.values()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not t.is_cancelled)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"\nTotal Revenue (active tickets): ₹{total:.2f}")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                system = TicketBookingSystem(total_seats=10)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    while True:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("\n===== TICKET BOOKING SYSTEM =====")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("1. Book Ticket")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("2. Cancel Ticket")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("3. Search Ticket")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("4. Display All Tickets")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("5. Check Seat Availability")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("6. Calculate Total Revenue")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("7. Exit")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            choice = input("Enter your choice: ")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if choice == '1':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                system.book_ticket()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif choice == '2':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    system.cancel_ticket()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif choice == '3':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        system.search_ticket()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif choice == '4':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            system.display_all_tickets()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif choice == '5':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                system.show_availability()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif choice == '6':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    system.calculate_revenue()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif choice == '7':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("Thank you for using our booking system! 🚆")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("Invalid choice! Please try again.")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            main()