import math


class Calculator:
    def add(self, a, b):
            return a + b

                def subtract(self, a, b):
                        return a - b

                            def multiply(self, a, b):
                                    return a * b

                                        def divide(self, a, b):
                                                if b == 0:
                                                            return "Error: Division by zero!"
                                                                    return a / b

                                                                        def modulus(self, a, b):
                                                                                if b == 0:
                                                                                            return "Error: Division by zero!"
                                                                                                    return a % b

                                                                                                        def power(self, a, b):
                                                                                                                return a ** b

                                                                                                                    def square_root(self, a):
                                                                                                                            if a < 0:
                                                                                                                                        return "Error: Cannot take square root of negative number!"
                                                                                                                                                return math.sqrt(a)

                                                                                                                                                    def factorial(self, a):
                                                                                                                                                            if a < 0:
                                                                                                                                                                        return "Error: Factorial not defined for negative numbers!"
                                                                                                                                                                                if a != int(a):
                                                                                                                                                                                            return "Error: Factorial only defined for whole numbers!"
                                                                                                                                                                                                    return math.factorial(int(a))


                                                                                                                                                                                                    def get_two_numbers():
                                                                                                                                                                                                        a = float(input("Enter first number : "))
                                                                                                                                                                                                            b = float(input("Enter second number: "))
                                                                                                                                                                                                                return a, b


                                                                                                                                                                                                                def get_one_number():
                                                                                                                                                                                                                    return float(input("Enter a number: "))


                                                                                                                                                                                                                    def main():
                                                                                                                                                                                                                        calc = Calculator()
                                                                                                                                                                                                                            history = []

                                                                                                                                                                                                                                while True:
                                                                                                                                                                                                                                        print("\n===== MENU-DRIVEN CALCULATOR =====")
                                                                                                                                                                                                                                                print(" 1. Addition          (+)")
                                                                                                                                                                                                                                                        print(" 2. Subtraction       (-)")
                                                                                                                                                                                                                                                                print(" 3. Multiplication    (*)")
                                                                                                                                                                                                                                                                        print(" 4. Division          (/)")
                                                                                                                                                                                                                                                                                print(" 5. Modulus           (%)")
                                                                                                                                                                                                                                                                                        print(" 6. Power             (^)")
                                                                                                                                                                                                                                                                                                print(" 7. Square Root       (√)")
                                                                                                                                                                                                                                                                                                        print(" 8. Factorial         (!)")
                                                                                                                                                                                                                                                                                                                print(" 9. View History")
                                                                                                                                                                                                                                                                                                                        print("10. Clear History")
                                                                                                                                                                                                                                                                                                                                print("11. Exit")

                                                                                                                                                                                                                                                                                                                                        choice = input("Enter your choice (1-11): ").strip()

                                                                                                                                                                                                                                                                                                                                                if choice == '1':
                                                                                                                                                                                                                                                                                                                                                            a, b   = get_two_numbers()
                                                                                                                                                                                                                                                                                                                                                                        result = calc.add(a, b)
                                                                                                                                                                                                                                                                                                                                                                                    print(f"Result: {a} + {b} = {result}")
                                                                                                                                                                                                                                                                                                                                                                                                history.append(f"{a} + {b} = {result}")

                                                                                                                                                                                                                                                                                                                                                                                                        elif choice == '2':
                                                                                                                                                                                                                                                                                                                                                                                                                    a, b   = get_two_numbers()
                                                                                                                                                                                                                                                                                                                                                                                                                                result = calc.subtract(a, b)
                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Result: {a} - {b} = {result}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                        history.append(f"{a} - {b} = {result}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif choice == '3':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            a, b   = get_two_numbers()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        result = calc.multiply(a, b)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"Result: {a} * {b} = {result}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                history.append(f"{a} * {b} = {result}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif choice == '4':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    a, b   = get_two_numbers()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                result = calc.divide(a, b)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Result: {a} / {b} = {result}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        history.append(f"{a} / {b} = {result}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif choice == '5':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            a, b   = get_two_numbers()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        result = calc.modulus(a, b)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"Result: {a} % {b} = {result}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                history.append(f"{a} % {b} = {result}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif choice == '6':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    a, b   = get_two_numbers()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                result = calc.power(a, b)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Result: {a} ^ {b} = {result}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        history.append(f"{a} ^ {b} = {result}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif choice == '7':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            a      = get_one_number()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        result = calc.square_root(a)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"Result: √{a} = {result}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                history.append(f"√{a} = {result}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif choice == '8':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    a      = get_one_number()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                result = calc.factorial(a)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Result: {a}! = {result}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        history.append(f"{a}! = {result}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif choice == '9':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not history:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("No calculations yet.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("\nCalculation History:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for i, record in enumerate(history, 1):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"  {i}. {record}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif choice == '10':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                history.clear()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("History cleared! ✅")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif choice == '11':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("Thank you for using the calculator! 🧮")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("Invalid choice! Please enter a number between 1-11.")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    main()